spring:
  datasource:
    url: jdbc:mysql://mysql-nelsonimor.alwaysdata.net/nelsonimor_prod_basket_stats_location?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: 130372_prod
    password: pernau84louise88
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none