spring:
  datasource:
    url: jdbc:mysql://mysql-nelsonimor.alwaysdata.net/nelsonimor_dev_basket_stats_location?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: 130372_dev
    password: pernau84louise88
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create