server:
  port: 8082

spring:
  application:
    name: Basketball-Statistics-Location
  profiles:
    # The active Spring profile can be filled in by maven or setting -Dspring.profiles.active` option in `JAVA_OPTS`
    active: #spring.profiles.active#