INSERT INTO t_region(name) VALUES ('Africa, Middle East');
INSERT INTO t_region(name) VALUES ('Antarctica');
INSERT INTO t_region(name) VALUES ('Arabian Peninsula, Middle East');
INSERT INTO t_region(name) VALUES ('Australia/Oceania');
INSERT INTO t_region(name) VALUES ('Balkan Peninsula');
INSERT INTO t_region(name) VALUES ('Balkan Peninsula, Southern Europe');
INSERT INTO t_region(name) VALUES ('Balkan, Eastern Europe');
INSERT INTO t_region(name) VALUES ('Caribbean');
INSERT INTO t_region(name) VALUES ('Caribbean, parts of the Bahamas island chain.');
INSERT INTO t_region(name) VALUES ('Caucasus');
INSERT INTO t_region(name) VALUES ('Caucasus, Western Asia');
INSERT INTO t_region(name) VALUES ('Central Africa');
INSERT INTO t_region(name) VALUES ('Central America');
INSERT INTO t_region(name) VALUES ('Central Asia');
INSERT INTO t_region(name) VALUES ('Central East South America');
INSERT INTO t_region(name) VALUES ('Central Eastern South America');
INSERT INTO t_region(name) VALUES ('Central South America');
INSERT INTO t_region(name) VALUES ('East-Central Africa');
INSERT INTO t_region(name) VALUES ('Eastern Africa');
INSERT INTO t_region(name) VALUES ('Eastern Africa, African Great Lakes');
INSERT INTO t_region(name) VALUES ('Eastern Asia');
INSERT INTO t_region(name) VALUES ('Eastern Europe');
INSERT INTO t_region(name) VALUES ('Eastern Europe - Northern Asia');
INSERT INTO t_region(name) VALUES ('Greater Antilles, Caribbean');
INSERT INTO t_region(name) VALUES ('Leeward Islands, Caribbean');
INSERT INTO t_region(name) VALUES ('Lesser Antilles, Caribbean');
INSERT INTO t_region(name) VALUES ('Maritime South-East Asia');
INSERT INTO t_region(name) VALUES ('Maritime Southeast Asia, Melanesia, Oceania');
INSERT INTO t_region(name) VALUES ('Mediterranean, Western Asia');
INSERT INTO t_region(name) VALUES ('Melanesia, Oceania');
INSERT INTO t_region(name) VALUES ('Micronesia, Oceania');
INSERT INTO t_region(name) VALUES ('Middle East');
INSERT INTO t_region(name) VALUES ('Middle East, Western Asia');
INSERT INTO t_region(name) VALUES ('North America');
INSERT INTO t_region(name) VALUES ('North Eastern South America');
INSERT INTO t_region(name) VALUES ('North North America');
INSERT INTO t_region(name) VALUES ('North West South America');
INSERT INTO t_region(name) VALUES ('North-Eastern South America');
INSERT INTO t_region(name) VALUES ('Northern Africa');
INSERT INTO t_region(name) VALUES ('Northern Europe');
INSERT INTO t_region(name) VALUES ('Northern South America');
INSERT INTO t_region(name) VALUES ('Northern South America, Caribbean');
INSERT INTO t_region(name) VALUES ('Oceania/Australia');
INSERT INTO t_region(name) VALUES ('Oceania; Australia');
INSERT INTO t_region(name) VALUES ('Polynesia, Oceania');
INSERT INTO t_region(name) VALUES ('South-Central Asia');
INSERT INTO t_region(name) VALUES ('South-East Asia');
INSERT INTO t_region(name) VALUES ('South-East Asia, Australia');
INSERT INTO t_region(name) VALUES ('Southeast Asia');
INSERT INTO t_region(name) VALUES ('Southeastern Europe, Western Asia');
INSERT INTO t_region(name) VALUES ('Southern Africa');
INSERT INTO t_region(name) VALUES ('Southern Europe');
INSERT INTO t_region(name) VALUES ('Southern Europe within Italy');
INSERT INTO t_region(name) VALUES ('Southern Indian Ocean');
INSERT INTO t_region(name) VALUES ('Southern South America');
INSERT INTO t_region(name) VALUES ('West Africa');
INSERT INTO t_region(name) VALUES ('Western Asia');
INSERT INTO t_region(name) VALUES ('Western Europe');
INSERT INTO t_region(name) VALUES ('Western South America');